version: '3.1'

services:
  reverseproxy:
    image: cbryant23/nginx-node
    container_name: nginx
    networks:
      - app-network
    ports:
      - 80
  nodejs:
    image: cbryant23/ip-api
    container_name: nodejs
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - .:/home/node/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
