version: '3.1'

services:
  reverseproxy:
    image: cbryant23/nginx-node
    container_name: nginx
    networks:
      - app-network
    ports:
      - 80
      - 4000
  graphapi:
    image: cbryant23/graph-api
    container_name: graphapi
    restart: unless-stopped
    deploy:
      replicas: 3
    ports:
      - 4000:8080
    networks:
      - app-network
    volumes:
      - ./api/dist:/app/node/api/dist
      - ./api/node_modules:/app/node/api/node_modules
  worker:
    image: cbryant23/node-worker
    container_name: worker
    restart: unless-stopped
    depends_on:
      - graphapi
    ports:
      - 80:3000
    networks:
      - app-network
    volumes:
      - ./worker/dist:/app/node/worker/dist
      - ./worker/client/build:/app/node/worker/client/build

networks:
  app-network:
    driver: overlay
