version: '3.1'

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
  nodejs:
    build:
      context: .
      dockerfile: typescript.Dockerfile
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASS
      - MONGO_HOST=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - PORT=8080
    ports:
      - '80:8080'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: node ./dist/server.js
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
