version: '3.1'

services:
  reverseproxy:
    image: nginx
    container_name: nginx
    ports:
      - 80:8080
  nodejs:
    build:
      context: .
      dockerfile: typescript.Dockerfile
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '80:8080'
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: node ./dist/server.js

networks:
  app-network:
    driver: bridge
